<a href="https://colab.research.google.com/github/Hiteshwalia4/Sem_3_MCA/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Practical 2
# Multiple Linear Regression ( 3 independent and 1 dependent variable)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("HousePrice.csv")

In [ ]:
df.head()

Area  Bedrooms  Construct      Price
0   2600.0       2.0       10.0   500000.0
1   4000.0       4.0       30.0   100000.0
2   8000.0       6.0        2.0   800000.0
3   3000.0       NaN       40.0   500000.0
4  10000.0       2.0        1.0  6000000.0

In [ ]:
df.isnull()

Area  Bedrooms  Construct  Price
0   False     False      False  False
1   False     False      False  False
2   False     False      False  False
3   False      True      False  False
4   False     False      False  False
5   False     False      False  False
6   False     False      False  False
7   False     False      False  False
8   False     False      False  False
9   False     False      False  False
10   True      True       True   True
11   True      True       True   True
12   True      True       True   True
13   True      True       True   True
14   True      True       True   True
15   True      True       True   True
16   True      True       True   True
17   True      True       True   True
18   True      True       True   True
19   True      True       True   True
20   True      True       True   True

In [ ]:
df.isnull().sum()

Area         11
Bedrooms     12
Construct    11
Price        11
dtype: int64

In [ ]:
df.shape

(21, 4)

In [ ]:
df=df.dropna()
df.shape

(9, 4)

In [ ]:
x=df.iloc[:,:-1].values
x

array([[2.6e+03, 2.0e+00, 1.0e+01],
       [4.0e+03, 4.0e+00, 3.0e+01],
       [8.0e+03, 6.0e+00, 2.0e+00],
       [1.0e+04, 2.0e+00, 1.0e+00],
       [1.0e+03, 3.0e+00, 5.0e+00],
       [5.0e+02, 2.0e+00, 8.0e+00],
       [2.0e+03, 2.0e+00, 1.0e+01],
       [8.0e+03, 2.0e+00, 2.0e+00],
       [5.0e+02, 3.0e+00, 6.0e+00]])

In [ ]:
y=df.iloc[:,-1].values
y

array([ 500000.,  100000.,  800000., 6000000.,  300000., 2500000.,
        450000.,  500000., 2000000.])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [ ]:
x_train

array([[5.0e+02, 2.0e+00, 8.0e+00],
       [2.6e+03, 2.0e+00, 1.0e+01],
       [5.0e+02, 3.0e+00, 6.0e+00],
       [8.0e+03, 6.0e+00, 2.0e+00],
       [1.0e+03, 3.0e+00, 5.0e+00],
       [1.0e+04, 2.0e+00, 1.0e+00],
       [2.0e+03, 2.0e+00, 1.0e+01]])

In [ ]:
x_test

array([[8.e+03, 2.e+00, 2.e+00],
       [4.e+03, 4.e+00, 3.e+01]])

In [ ]:
y_train

array([2500000.,  500000., 2000000.,  800000.,  300000., 6000000.,
        450000.])

In [ ]:
y_test

array([500000., 100000.])

In [ ]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=reg.predict(x_test)
y_pred

array([  5201300.5039761 , -10300888.37213547])

In [ ]:
# Difference b/w predicted values and actual values
y_pred-y_test

array([  4701300.5039761 , -10400888.37213547])